version = 0.1
[default.deploy.parameters]
stack_name = "simple-lambda-layer"
resolve_s3 = true
s3_prefix = "simple-lambda-layer"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
