AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Layer Demo for Python and Node.js

Resources:
  PythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/
      Handler: lambda.handler
      Runtime: python3.12
      Layers:
        - !Ref PythonDependenciesLayer

  NodejsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs/
      Handler: lambda.handler
      Runtime: nodejs18.x
      Layers:
        - !Ref NodejsDependenciesLayer

  PythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: python-dependencies-layer
      Description: Dependencies for the Python Lambda function
      ContentUri: python/layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  NodejsDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodejs-dependencies-layer
      Description: Dependencies for the Node.js Lambda function
      ContentUri: nodejs/layer/
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain

Outputs:
  PythonFunction:
    Description: "Python Lambda Function ARN"
    Value: !GetAtt PythonFunction.Arn
  NodejsFunction:
    Description: "Node.js Lambda Function ARN"
    Value: !GetAtt NodejsFunction.Arn